# Modules, Packages and Libraries
#### Python Modules
A module is basically a bunch of related code saved in a file with the extension `.py`. You may choose to define functions, classes, or variables in a module. If we want to use the code defined in a module in our application, we first need to import the respective module using the **`import`** statement. Then, we’ll be ready to use a function defined in this module by calling that function with the `module.function()` syntax.

#### Python Packages
*`Python packages are basically a directory of a collection of modules.`* Packages allow the hierarchical structure of the module namespace. Just like we organize our files on a hard drive into folders and sub-folders, we can organize our modules into packages and subpackages.

#### Python Libraries
*`A library is an umbrella term referring to a reusable chunk of code.`* Usually, a Python library contains a collection of related modules and packages. Actually, this term is often used interchangeably with “Python package” because packages can also contain modules and other packages (subpackages). However, it is often assumed that while *`a package is a collection of modules, a library is a collection of packages.`*

Source:
https://learnpython.com/blog/python-modules-packages-libraries-frameworks/

## Creating Your Own Modules

**Example:** module is in `the same directory` as the program which needs to use functions from other modules

In [1]:
# The file myprog.py is in the same folder as this Jupyter notebook
import myprog
print(myprog.increment(2,3))

5


**Example:** module is in a different directory than the program which needs to use functions from other modules

In [5]:
# The file mymodule.py is in the folder "myfolder" which is 
# in the same location as this Jupyter notebook
from myfolder import mymodule # This used very often
print(mymodule.even_check([2,4,6]))

#print(even_check([2,4,6]) does not work!!!

True


**Example:** module is in a different directory than the program which needs to use functions from other modules

In [7]:
import myfolder
print(mymodule.even_check([1,3,5]))

# Clearer 
import myfolder
print(myfolder.mymodule.even_check([1,2,3,4]))

False
False


**Examples: Give a shortcut name to the module**

Note: this is extreamly useful for modules with long names such as matplotlib

In [11]:
import myfolder as mf
print(mf.mymodule.even_check([20,3]))

# Clear and convinent
import myfolder.mymodule as mmod
print(mmod.even_check([2,3]))

False
False


**Examples: import function(s) or everything in a given module** 

Note: you `don't need` to refer the module name when calling the function.

In [13]:
# Only import certain function
from myfolder.mymodule import even_check
print(even_check([2,4,6]))

# Import everything including function
from myprog import *
print(increment(3,5))

True
8


## Python Libraries for Data Science: Numpy, Pandas and Matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

### 1. Numpy
#### Numpy Array

In [ ]:
### Create a 1 dimensional array
a = np.array([1,2,3])

### Print object type
print(type(a))

### Print shape
print(a.shape)

### Print some values in a
print(a[0], a[1], a[2])

### Create a 2x2 numpy array
b = np.array([[1,2],[3,4]])

### Print shape
print(b.shape)

## Print some values in b
print(b[0,0], b[0,1], b[1,1])

### Create a 3x2 numpy array
c = np.array([[1,2],[3,4],[5,6]])

### Print shape
print(c.shape)

### Print some values in c
print(c[0,1], c[1,0], c[2,0], c[2,1])

**Numpy.random.random(): a function used `very often`!**

In [ ]:
### Generate a 3 x 3 array of random floating point numbers in the range [0.0, 1.0).
g = np.random.random((3,3))
print(g)

In [ ]:
# random.randint(low, high, size): low and size are optional

# Generate a random integer value between 0 and 9 inclusive
print(np.random.randint(10))

# Generate a 4 x 3 array of ints between 0 and 4, inclusive:
print(np.random.randint(5, size=(4,3)))

#### Array Math (Optional)
Basic mathematical functions operate **`elementwise`** on arrays, and are available both as `operator overloads` and as `functions` in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

#### Np.sum() and np.mean() (optional)

In [ ]:
x = np.array([[1,2],[3,4]])

### Compute sum of all elements; prints "10"
print(np.sum(x))

### Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=0)) 

### Compute sum of each row; prints "[3 7]"
print(np.sum(x, axis=1))

In [ ]:
x = np.array([[1,2],[3,4]])

### Compute mean of all elements; prints "2.5"
print(np.mean(x))

### Compute mean of each column; prints "[2 3]"
print(np.mean(x, axis=0)) 

### Compute mean of each row; prints "[1.5 3.5]"
print(np.mean(x, axis=1))

### 2. Pandas

**Example:** Constructing a dataframe from list of lists

In [ ]:
# Create a 4x2 nested list - data are grouped by row
nested_list = [['Henry Wolf', 45],['John Miller', 27],['Mary Wong', 38],['Alice Wilson', 63]]

# Construct a dataframe from list of lists
df1 = pd.DataFrame(data=nested_list, columns=['Name', 'Age'])
df1

In [ ]:
# Don't save the extra row index
df1.to_csv('file1.csv', index=False)

In [ ]:
df = pd.read_csv('file1.csv')
df

**Exaple:** Constructing a dataframe from a dictionary

In [ ]:
# Note: data are grouped by column. Dictionary keys are the column name.
my_dict = {'Fruit': ['Apple', 'Banana', 'Grape', 'Peach'], 'Price/Lb':[1.99, 0.65, 2.99, 3.99]}
pd.DataFrame(data=my_dict)

**Exaple:** Constructing a dataframe from a numpy array

In [ ]:
import numpy as np

np_arr = np.array([['F', 68, 98], ['M', 95, 70], ['F', 85, 96], ['M', 92, 80]])
pd.DataFrame(data=np_arr, columns=['Gender', 'Score1', 'Sore2'])

### 3. Matplotlib

In [ ]:
# http://matplotlib.org/examples/index.html
# https://matplotlib.org/2.0.2/examples/pylab_examples/hist2d_demo.html
import matplotlib.pyplot as plt
import numpy as np

# normal distribution center at x1=0 and y1=5
x1 = np.random.randn(1000)
y1 = np.random.randn(1000) + 5


plt.hist2d(x=x1, y=y1, bins=40)
plt.show()

In [ ]:
# Other common plots
plt.scatter(x1, y1, alpha=0.3)
plt.show()

plt.hist(x1)
plt.hist(y1)
plt.show()

plt.boxplot(x1)
plt.show()

In [ ]:
#define some data
x2 = [1,2,3,4]
y2 = [20, 21, 20.5, 20.8]

#plot data
plt.plot(x2, y2)

plt.show()

## Sqlite3: Python Package for Writing to and Reading from Databases

In [ ]:
import sqlite3

# Create a connection to sqlite
conn = sqlite3.connect('test1.db')

# Open a cursor
c = conn.cursor()

# Execute any SQL statement
# Create table named "stocks" if it does not already exist.
c.execute("create table if not exists stocks \
           (date text, trans text,symbol text, qty real, price real)")

# Add entries
c.execute("insert into stocks values ('2006-02-05','SELL','RHAT',50,50.25)")
c.execute("insert into stocks values ('2006-03-15','BUY','GOOG',1000,350.13)")
c.execute("insert into stocks values ('2006-10-05','BUY','GOOG',100000,400.14)")
conn.commit()

# Query all the entries in the database
alllines = c.execute("select * from stocks")
print("All lines: ", alllines)

# Print it
for lines in alllines:
    print("Line:", lines)

c.close()

## OS: Module Provides Functions for Interacting with the Operating System

In [2]:
import os

os.listdir(".")

['.ipynb_checkpoints',
 'Capstone-Project.ipynb',
 'FCSN_Python_0501_Modules.ipynb',
 'file1.csv',
 'file2.csv',
 'file2.txt',
 'myfolder',
 'myprog.py',
 'test1.db',
 '__pycache__']

In [6]:
pwd

'C:\\Users\\huiyi\\FCSN\\Python_Course\\05-Modules and Packages'

In [3]:
os.listdir('C:\\Users\\huiyi\\FCSN\\Python_Course\\05-Modules and Packages')

['.ipynb_checkpoints',
 'Capstone-Project.ipynb',
 'FCSN_Python_0501_Modules.ipynb',
 'file1.csv',
 'file2.csv',
 'file2.txt',
 'myfolder',
 'myprog.py',
 'test1.db',
 '__pycache__']

In [4]:
for root, dirs, files in os.walk('C:\\Users\\huiyi\\FCSN\\Python_Course\\05-Modules and Packages'):
    print("This is root: ", root)
    print("This is dirs: ", dirs)
    # root, dirs, files
    for file in files:
        if file.endswith(".py"):
             print(os.path.join(root, file))

This is root:  C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages
This is dirs:  ['.ipynb_checkpoints', 'myfolder', '__pycache__']
C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\myprog.py
This is root:  C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\.ipynb_checkpoints
This is dirs:  []
This is root:  C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\myfolder
This is dirs:  ['.ipynb_checkpoints', '__pycache__']
C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\myfolder\mymodule.py
This is root:  C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\myfolder\.ipynb_checkpoints
This is dirs:  []
This is root:  C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\myfolder\__pycache__
This is dirs:  []
This is root:  C:\Users\huiyi\FCSN\Python_Course\05-Modules and Packages\__pycache__
This is dirs:  []


In [5]:
os.getcwd()

'C:\\Users\\huiyi\\FCSN\\Python_Course\\05-Modules and Packages'

## Math

In [7]:
# Import all functions in a given module
# You have to refer to the module name when 
# calling the function
import math
print(math.sin(math.pi/4))

0.7071067811865476


In [8]:
# Import all functions in a given module
# You do not need to refer to the module name when 
# calling the function
from math import *
print(sin(pi/4))

0.7071067811865476


In [10]:
# Give a shortcut name to the module. 
# Especially true for modules with long names such as matplotlib
import math as ma
print(ma.sin(ma.pi/4))

0.7071067811865476


In [11]:
# Only import the necessary functions from a module
# This is memory efficient
from math import sin,pi
print(sin(pi/4))

0.7071067811865476


## Datetime: Module for Manipulating Dates and Times

In [ ]:
import datetime

In [ ]:
# Create a Python time object hour=8, minute=30, seconds = 0
t = datetime.time(8,30,0)
print(t)

In [ ]:
# Create a Python date object year = 2022, month = 12 and day = 6
d = datetime.date(year=2022, month=12, day=6)
print(d)

In [ ]:
# Print current date
print(datetime.date.today())

In [ ]:
td = datetime.date.today() # Todays date
tomd = datetime.date.today()+datetime.timedelta(days=1) # Tomorrows date
print(td,tomd)

In [ ]:
# If you want both date and time
today = datetime.datetime.today()
print(today)